#!/bin/bash
RANGE=42

number=$RANDOM
let "number %= $RANGE"
case $number in
0) cow="beavis.zen ";;
1) cow="bud-frogs ";;
2) cow="bunny ";;
3) cow="cheese ";;
4) cow="daemon ";;
5) cow="default ";;
6) cow="dragon";;
7) cow="dragon-and-cow ";;
8) cow="elephant ";;
9) cow="elephant-in-snake ";;
10) cow="eyes ";;
11) cow="flaming-sheep ";;
12) cow="ghostbusters";;
13) cow="head-in ";;
14) cow="hellokitty ";;
15) cow="kiss ";;
16) cow="kitty ";;
17) cow="koala ";;
18) cow="kosh ";;
19) cow="luke-koala ";;
20) cow="mech-and-cow ";;
21) cow="meow ";;
22) cow="milk";;
23) cow="moofasa ";;
24) cow="moose ";;
25) cow="mutilated ";;
26) cow="ren ";;
27) cow="satanic ";;
28) cow="sheep ";;
29) cow="skeleton ";;
30) cow="small ";;
31) cow="sodomized";;
32) cow="stegosaurus ";;
33) cow="stimpy ";;
34) cow="three-eyes ";;
35) cow="turkey ";;
36) cow="turtle";;
37) cow="tux ";;
38) cow="udder ";;
39) cow="vader ";;
40) cow="vader-koala ";;
41) cow="www";;
esac

fortune | cowsay -f $cow

